In [28]:
import numpy as np
import pandas as pd

df = pd.read_csv("Data/Raw/customer_churn_data.csv")
df.head()

,customer_id,gender,age,tenure_months,contract_type,monthly_charges,payment_method,internet_service,support_tickets,complaints,avg_monthly_usage_gb,login_frequency,discount_percent,satisfaction_score,late_payments,total_charges,churn,satifaction_score
0,CUST00001,Male,68,26,Two Year,1315.66,Debit Card,NaN,2,2,310.00,30,20,1,1,27365.73,0,NaN
1,CUST00002,Female,64,48,One Year,4660.91,Credit Card,Fiber,3,1,226.32,9,15,8,0,190165.13,0,NaN
2,CUST00003,Male,64,19,Monthly,966.19,Debit Card,Fiber,1,2,67.11,13,15,6,0,15603.97,0,NaN
3,CUST00004,Male,21,9,Monthly,2943.45,UPI,Fiber,1,0,408.99,8,5,4,2,25166.50,0,NaN
4,CUST00005,Male,24,64,One Year,1913.04,Bank Transfer,Fiber,4,2,147.09,17,15,6,1,104069.38,0,NaN

In [29]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 5000
Columns: 18

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           5000 non-null   str
 1   gender                5000 non-null   str
 2   age                   5000 non-null   int64
 3   tenure_months         5000 non-null   int64
 4   contract_type         5000 non-null   str
 5   monthly_charges       4900 non-null   float64
 6   payment_method        4900 non-null   str
 7   internet_service      4142 non-null   str
 8   support_tickets       5000 non-null   int64
 9   complaints            5000 non-null   int64
 10  avg_monthly_usage_gb  5000 non-null   float64
 11  login_frequency       5000 non-null   int64
 12  discount_percent      5000 non-null   int64
 13  satisfaction_score    5000 non-null   int64
 14  late_payments         5000 non-null   int64
 15  total_charges         4900 non-null   float64
 16  churn                 5000 non-null   int64
 17  satifaction_score     0 non-null      float64
dtypes: float64(4), int64(9), str(5)
memory usage: 703.3 KB

In [31]:
df.isnull().sum()

customer_id                0
gender                     0
age                        0
tenure_months              0
contract_type              0
monthly_charges          100
payment_method           100
internet_service         858
support_tickets            0
complaints                 0
avg_monthly_usage_gb       0
login_frequency            0
discount_percent           0
satisfaction_score         0
late_payments              0
total_charges            100
churn                      0
satifaction_score       5000
dtype: int64

In [32]:
missing_percentage = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)
missing_percentage

satifaction_score       100.00
internet_service         17.16
total_charges             2.00
monthly_charges           2.00
payment_method            2.00
customer_id               0.00
gender                    0.00
tenure_months             0.00
contract_type             0.00
age                       0.00
complaints                0.00
support_tickets           0.00
avg_monthly_usage_gb      0.00
login_frequency           0.00
satisfaction_score        0.00
discount_percent          0.00
late_payments             0.00
churn                     0.00
dtype: float64

In [33]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [34]:
df.describe()

,age,tenure_months,monthly_charges,support_tickets,complaints,avg_monthly_usage_gb,login_frequency,discount_percent,satisfaction_score,late_payments,total_charges,churn,satifaction_score
count,5000.000000,5000.000000,4900.000000,5000.000000,5000.0000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,4900.000000,5000.000000,0.0
mean,43.894800,36.602200,2722.558682,1.998000,0.9996,255.938402,15.511400,6.731000,5.440400,0.994000,93384.868131,0.217400,NaN
std,15.158882,20.841344,1291.037545,1.416332,0.9997,144.097870,8.736655,6.314793,2.860155,0.996074,74823.270935,0.412518,NaN
min,18.000000,1.000000,500.040000,0.000000,0.0000,5.130000,1.000000,0.000000,1.000000,0.000000,475.750000,0.000000,NaN
25%,31.000000,18.000000,1601.547500,1.000000,0.0000,129.692500,8.000000,0.000000,3.000000,0.000000,33590.757500,0.000000,NaN
50%,43.000000,36.000000,2706.835000,2.000000,1.0000,258.035000,15.000000,5.000000,5.000000,1.000000,72487.860000,0.000000,NaN
75%,57.000000,55.000000,3818.200000,3.000000,2.0000,384.172500,23.000000,10.000000,8.000000,2.000000,138335.275000,0.000000,NaN
max,70.000000,72.000000,4998.630000,10.000000,6.0000,499.840000,30.000000,20.000000,10.000000,6.000000,354453.120000,1.000000,NaN

In [35]:
df.drop(columns=["satifaction_score"], inplace=True)
print(df.shape)

(5000, 17)

In [36]:
df.isnull().sum()

customer_id               0
gender                    0
age                       0
tenure_months             0
contract_type             0
monthly_charges         100
payment_method          100
internet_service        858
support_tickets           0
complaints                0
avg_monthly_usage_gb      0
login_frequency           0
discount_percent          0
satisfaction_score        0
late_payments             0
total_charges           100
churn                     0
dtype: int64

In [37]:
print("Duplicate customer IDs:", df["customer_id"].duplicated().sum())

Duplicate customer IDs: 0

In [38]:
df["monthly_charges"] = df["monthly_charges"].fillna(
    df["monthly_charges"].median()
)

df["total_charges"] = df["total_charges"].fillna(
    df["total_charges"].median()
)

In [39]:
df["payment_method"] = df["payment_method"].fillna("Unknown")

df["internet_service"] = df["internet_service"].fillna("Unknown")

In [40]:
df.isnull().sum()

customer_id             0
gender                  0
age                     0
tenure_months           0
contract_type           0
monthly_charges         0
payment_method          0
internet_service        0
support_tickets         0
complaints              0
avg_monthly_usage_gb    0
login_frequency         0
discount_percent        0
satisfaction_score      0
late_payments           0
total_charges           0
churn                   0
dtype: int64

In [41]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customer IDs:", df["customer_id"].duplicated().sum())

Duplicate rows: 0
Duplicate customer IDs: 0

In [42]:
import os

os.makedirs("Data/Processed", exist_ok=True)

df.to_csv(
    "Data/Processed/customer_churn_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [43]:
import os

print(os.path.exists("Data/Raw/customer_churn_data.csv"))

True